# Not tested
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "flux-101.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules: # subdomain, path
  - http:
      paths:
      - path: /v1
        backend:
          serviceName: {{ include "flux-101.fullname" . }}
          servicePort: {{ .Values.service.port }}

  - host: v1.my-cluster.io
    http:
      paths:
        - backend:
            serviceName: {{ include "flux-101.fullname" . }}
            servicePort: {{ .Values.service.port }}

